# Generated by Django 4.0.4 on 2022-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_core', '0003_remove_choice_elective_groups_block_capacity_and_more'),
        ('elnure_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elective_groups',
            field=models.ManyToManyField(help_text='Elective groups attached to the student after groups formation', related_name='students', through='elnure_core.ElectiveGroupStudentAssociation', to='elnure_core.electivegroup'),
        ),
    ]
