# Generated by Django 4.0.4 on 2022-05-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_users', '0002_user_elective_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('elnure_users.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Whether user should be admin'),
        ),
    ]
