# Generated by Django 4.0.5 on 2022-06-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_users', '0003_student_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='start_year',
            field=models.PositiveIntegerField(default=2018, help_text='Year when student group was formed'),
            preserve_default=False,
        ),
    ]
