# Generated by Django 4.0.5 on 2022-06-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_users', '0004_academicgroup_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='elnure_users.academicgroup'),
        ),
    ]
