# Generated by Django 4.0.4 on 2022-05-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'application_windows',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveIntegerField(help_text='Id should be equal to the number of the semester.', primary_key=True, serialize=False)),
                ('total_credits', models.PositiveIntegerField(help_text='How many credits in total should be covered by electives')),
                ('study_year', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'semesters',
            },
        ),
    ]
