# Generated by Django 4.0.4 on 2022-05-28 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elnure_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elnure_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='elective_course_choices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='semester',
            field=models.ForeignKey(help_text='Semester of block', on_delete=django.db.models.deletion.RESTRICT, related_name='blocks', to='elnure_config.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('student', 'application_window')},
        ),
    ]
