# Generated by Django 4.0.4 on 2022-05-22 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_core', '0002_alter_choice_elective_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='study_year',
            field=models.PositiveIntegerField(help_text='Study year of elective courses which student applies for', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
