# Generated by Django 4.0.4 on 2022-05-29 22:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import elnure_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_core', '0003_remove_choice_elective_groups_block_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategysnapshot',
            old_name='application_window_snapshot',
            new_name='application_window',
        ),
        migrations.RemoveField(
            model_name='electivecourse',
            name='is_professional',
        ),
        migrations.RemoveField(
            model_name='electivecourse',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='strategysnapshot',
            name='semesters_snapshot',
        ),
        migrations.AddField(
            model_name='block',
            name='must_choose',
            field=models.PositiveIntegerField(default=1, help_text='Number of elective courses that have to be choosen in block', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategysnapshot',
            name='need_redistribution',
            field=models.JSONField(default=list, help_text='Students who are not automatically distributed and need to be manually added to result.'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='strategy',
            field=elnure_common.fields.ElnureEnumField(choices=[('DEFAULT', 'Default')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='electivecourse',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_courses', to='elnure_core.block'),
        ),
        migrations.AlterField(
            model_name='electivecourse',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='electivecourse',
            name='shortcut',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='strategysnapshot',
            name='strategy',
            field=elnure_common.fields.ElnureEnumField(choices=[('DEFAULT', 'Default')], max_length=7),
        ),
    ]
