# Generated by Django 4.0.4 on 2022-05-23 21:57

from django.db import migrations, models
import django.db.models.deletion
import elnure_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_core', '0004_alter_block_credits_alter_choice_study_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='strategy',
            field=elnure_common.fields.ElnureEnumField(choices=[('DEFAULT', 'Default'), ('OPTIMIZED', 'Optimized')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.JSONField(help_text='Value to be processed in one of the descendants of BaseChoiceStrategy'),
        ),
        migrations.CreateModel(
            name='StrategyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', elnure_common.fields.ElnureEnumField(choices=[('DEFAULT', 'Default'), ('OPTIMIZED', 'Optimized')], max_length=9)),
                ('value', models.JSONField(help_text='List of lective groups for elective subjects with students')),
                ('application_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_run_results', to='elnure_core.applicationwindow')),
            ],
            options={
                'db_table': 'strategy_results',
            },
        ),
    ]
