# Generated by Django 4.0.5 on 2022-06-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_core', '0006_runsnapshot_create_date_runsnapshot_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivegroup',
            name='start_year',
            field=models.PositiveIntegerField(default=2018, help_text='Year when student group was formed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electivegroupstudentassociation',
            name='choice',
            field=models.ForeignKey(blank=True, help_text='Student choice which this asssociation is created for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_distributions', to='elnure_core.choice'),
        ),
    ]
