# Generated by Django 4.0.5 on 2022-06-06 15:51

from django.db import migrations
import elnure_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_core', '0007_electivegroup_start_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsnapshot',
            name='status',
            field=elnure_common.fields.ElnureEnumField(choices=[('PRESERVED', 'Preserved'), ('DRAFT', 'Draft')], default='DRAFT', max_length=9),
        ),
    ]
