# Generated by Django 4.0.5 on 2022-06-06 16:20

from django.db import migrations
import elnure_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_core', '0008_runsnapshot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runsnapshot',
            name='status',
            field=elnure_common.fields.ElnureEnumField(choices=[('ACCEPTED', 'Accepted'), ('DRAFT', 'Draft')], default='DRAFT', max_length=8),
        ),
    ]
