# Generated by Django 4.0.5 on 2022-06-06 19:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elnure_core', '0009_alter_runsnapshot_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electivegroupstudentassociation',
            unique_together={('elective_group', 'student', 'choice')},
        ),
    ]
