# Generated by Django 4.0.5 on 2022-06-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_core', '0010_alter_electivegroupstudentassociation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runsnapshot',
            name='need_redistribution',
            field=models.JSONField(blank=True, default=dict, help_text='Students who are not automatically distributed and need to be manually added to result.'),
        ),
        migrations.AlterField(
            model_name='runsnapshot',
            name='result',
            field=models.JSONField(default=dict, help_text='List of elective groups for elective subjects with students'),
        ),
    ]
