# Generated by Django 4.0.5 on 2022-06-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_core', '0011_alter_runsnapshot_need_redistribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
