# Generated by Django 4.0.5 on 2022-06-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elnure_core', '0012_block_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='description',
        ),
    ]
