# Generated by Django 4.0.5 on 2022-06-16 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elnure_core', '0015_alter_choice_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_course_choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
